FROM ghcr.io/linuxserver/baseimage-selkies:ubuntunoble

ENV TITLE=waydroid
ENV PIXELFLUX_WAYLAND=true
ENV WAYLAND_DISPLAY=wayland-1

RUN apt-get update && \
  apt-get install -y curl ca-certificates kmod lsb-release xwayland adb && \
  curl -s https://repo.waydro.id | bash && \
  apt-get install -y waydroid && \
  rm -rf /var/lib/apt/lists/*

COPY /root /

EXPOSE 3001
VOLUME /config
